version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./:/var/www
      # - node_modules:/var/www/node_modules
    ports:
      - "8080:8080"
    restart: always
    tty: true

# volumes:
#   node_modules:
